// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByTwZ6uF-GsDy8M2kg4XwCiJwYz0In1ok',
    appId: '1:145844906394:web:b4acf088a82490cb88b223',
    messagingSenderId: '145844906394',
    projectId: 'kojiwixford',
    authDomain: 'kojiwixford.firebaseapp.com',
    storageBucket: 'kojiwixford.firebasestorage.app',
    measurementId: 'G-QE4LJ6T714',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOiRp0n79u9a0rKkfvZMvlZly1da06wYs',
    appId: '1:145844906394:android:0353cfd3a74a0c0888b223',
    messagingSenderId: '145844906394',
    projectId: 'kojiwixford',
    storageBucket: 'kojiwixford.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjf2eaojCTSaDVB89_JGhS3L6CkSra_P8',
    appId: '1:145844906394:ios:f43f745bb196831788b223',
    messagingSenderId: '145844906394',
    projectId: 'kojiwixford',
    storageBucket: 'kojiwixford.firebasestorage.app',
    iosBundleId: 'com.example.koji',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByTwZ6uF-GsDy8M2kg4XwCiJwYz0In1ok',
    appId: '1:145844906394:web:dd48cc2f3fa734d788b223',
    messagingSenderId: '145844906394',
    projectId: 'kojiwixford',
    authDomain: 'kojiwixford.firebaseapp.com',
    storageBucket: 'kojiwixford.firebasestorage.app',
    measurementId: 'G-HY6W3R8YQ4',
  );
}
